name: businet
description: The crowdfunding app of Africa 

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  image_picker: ^0.8.4+4
  provider: ^6.0.2
  path_provider: ^2.0.8
  google_fonts: ^2.2.0
  kkiapay_flutter_sdk: ^1.0.6
  flutter_webview_plugin: ^0.4.0
  url_launcher: ^6.0.17
  introduction_screen: ^2.1.0
  cached_network_image: ^3.2.0
  permission_handler: ^8.3.0
  connectivity: ^3.0.0
  badges: ^2.0.2
  dots_indicator: ^2.0.0
  flutter_custom_tabs: ^1.0.1
  flutter_icons: ^1.1.0
  shared_preferences: ^2.0.10
  bubble_tab_indicator: ^0.1.6
  flutter_screenutil: ^5.0.3
  slide_to_act: ^2.0.1
  animated_progress_button: ^1.0.2+1
  rounded_loading_button: ^2.0.9
  material_design_icons_flutter: ^5.0.6595
  percent_indicator: ^3.4.0
  fluttertoast: ^8.0.6
  flutter_svg: ^1.0.0
  share: ^2.0.4
  toast: ^0.1.5
  skeleton_text: ^3.0.0
  package_info: ^2.0.2
  md2_tab_indicator: ^1.0.2
  lottie: ^1.2.1
  line_icons: ^2.0.1
  launch_review: ^3.0.1
  google_sign_in: ^4.4.6
  apple_sign_in: ^0.1.0
  easy_localization: ^3.0.0
  youtube_player_flutter: ^8.0.0
  html: ^0.15.0
  html_unescape: ^2.0.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  firebase_messaging: ^11.2.5
  cloud_functions: ^3.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/businet.png"

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/translations/
    - assets/images/
    - assets/images/linkedin/icons/
    - assets/images/linkedin/users/
    - assets/images/linkedin/posts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500

    - family: Hellix Bold
      fonts:
        - asset: assets/fonts/Hellix-Bold.ttf
          weight: 500

    - family: Manrope
      fonts:
        # - asset: assets/fonts/Manrope-Light.ttf
        #   weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900

    - family: avenir
      fonts:
        - asset: assets/fonts/avenirMedium.ttf
  